//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notes.Resouces.dictionary", typeof(dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.js.
        /// </summary>
        public static string _lng {
            get {
                return ResourceManager.GetString("_lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация пользователя.
        /// </summary>
        public static string BtnRegNewUser {
            get {
                return ResourceManager.GetString("BtnRegNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовать.
        /// </summary>
        public static string CbxPublic {
            get {
                return ResourceManager.GetString("CbxPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи.
        /// </summary>
        public static string MenuLogFile {
            get {
                return ResourceManager.GetString("MenuLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями, через администратора.
        /// </summary>
        public static string MenuManage {
            get {
                return ResourceManager.GetString("MenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметка.
        /// </summary>
        public static string MenuNoteAdd {
            get {
                return ResourceManager.GetString("MenuNoteAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список.
        /// </summary>
        public static string MenuNoteList {
            get {
                return ResourceManager.GetString("MenuNoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string MenuRegistration {
            get {
                return ResourceManager.GetString("MenuRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string MenuUser {
            get {
                return ResourceManager.GetString("MenuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректный адрес электронной почты.
        /// </summary>
        public static string ModelEmailWrong {
            get {
                return ResourceManager.GetString("ModelEmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string ModelPasswordDisplay {
            get {
                return ResourceManager.GetString("ModelPasswordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется указать пароль.
        /// </summary>
        public static string ModelPasswordRequired {
            get {
                return ResourceManager.GetString("ModelPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не соответствует уровню сложности.
        /// </summary>
        public static string ModelPasswordWrong {
            get {
                return ResourceManager.GetString("ModelPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string ModelRememberMeDisplay {
            get {
                return ResourceManager.GetString("ModelRememberMeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string ModelUserNameDisplay {
            get {
                return ResourceManager.GetString("ModelUserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется указать имя пользователя.
        /// </summary>
        public static string ModelUserNameRequired {
            get {
                return ResourceManager.GetString("ModelUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендуется использовать в качестве имени входа адрес электронной почты..
        /// </summary>
        public static string MsgLine1 {
            get {
                return ResourceManager.GetString("MsgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это сделает позволит сделать вход в систему более удобным..
        /// </summary>
        public static string MsgLine2 {
            get {
                return ResourceManager.GetString("MsgLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для простоты запоминания и получения возможности восстановления пароля..
        /// </summary>
        public static string MsgLine3 {
            get {
                return ResourceManager.GetString("MsgLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить сообщение.
        /// </summary>
        public static string NavAddNote {
            get {
                return ResourceManager.GetString("NavAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории сообщений.
        /// </summary>
        public static string NavCategories {
            get {
                return ResourceManager.GetString("NavCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неопределенные.
        /// </summary>
        public static string NavDnDef {
            get {
                return ResourceManager.GetString("NavDnDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все сообщения.
        /// </summary>
        public static string NavFullList {
            get {
                return ResourceManager.GetString("NavFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные.
        /// </summary>
        public static string NavPrivate {
            get {
                return ResourceManager.GetString("NavPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичные.
        /// </summary>
        public static string NavPublic {
            get {
                return ResourceManager.GetString("NavPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string PageTitleMain {
            get {
                return ResourceManager.GetString("PageTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string PhlAuthor {
            get {
                return ResourceManager.GetString("PhlAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст заметки.
        /// </summary>
        public static string PhlBody {
            get {
                return ResourceManager.GetString("PhlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string PhlCreateDate {
            get {
                return ResourceManager.GetString("PhlCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string PhlEmailAddress {
            get {
                return ResourceManager.GetString("PhlEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер записи.
        /// </summary>
        public static string PhlNoteId {
            get {
                return ResourceManager.GetString("PhlNoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PhlPassword {
            get {
                return ResourceManager.GetString("PhlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по ключевому слову.
        /// </summary>
        public static string PhlSearch {
            get {
                return ResourceManager.GetString("PhlSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок статьи.
        /// </summary>
        public static string PhlTitle {
            get {
                return ResourceManager.GetString("PhlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string PhlUserName {
            get {
                return ResourceManager.GetString("PhlUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для регистрации свяжитесь с администратором.
        /// </summary>
        public static string PpvCallAdmin {
            get {
                return ResourceManager.GetString("PpvCallAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба регистрации.
        /// </summary>
        public static string PpvRegService {
            get {
                return ResourceManager.GetString("PpvRegService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string ThDate {
            get {
                return ResourceManager.GetString("ThDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список заметок с.
        /// </summary>
        public static string ThListFrom {
            get {
                return ResourceManager.GetString("ThListFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №№.
        /// </summary>
        public static string ThListId {
            get {
                return ResourceManager.GetString("ThListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string ThListOf {
            get {
                return ResourceManager.GetString("ThListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по.
        /// </summary>
        public static string ThListTo {
            get {
                return ResourceManager.GetString("ThListTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С уважением, администрация.
        /// </summary>
        public static string TtlAdminSign {
            get {
                return ResourceManager.GetString("TtlAdminSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокнот.
        /// </summary>
        public static string TtlBrandName {
            get {
                return ResourceManager.GetString("TtlBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист сообщений.
        /// </summary>
        public static string TtlListNotes {
            get {
                return ResourceManager.GetString("TtlListNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение входа.
        /// </summary>
        public static string TtlLogin {
            get {
                return ResourceManager.GetString("TtlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с локальной учетной записью.
        /// </summary>
        public static string TtlLoginLocal {
            get {
                return ResourceManager.GetString("TtlLoginLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение для пользователей.
        /// </summary>
        public static string TtlMessageForUsers {
            get {
                return ResourceManager.GetString("TtlMessageForUsers", resourceCulture);
            }
        }
    }
}
